app-id: io.github.angelfor3v3r.phys
runtime: org.freedesktop.Platform
runtime-version: '25.08'
sdk: org.freedesktop.Sdk
command: phys

finish-args:
  - --share=ipc
  - --device=dri
  - --socket=fallback-x11
  - --socket=wayland

build-options:
  build-args:
    - --share=network

modules:
  - name: phys
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DPHYS_AVX2=OFF
    sources:
      - type: dir
        path: ../../
